"""Initial migration with all models including care plan tables

Revision ID: 2ffe5d3fee03
Revises: 
Create Date: 2025-11-21 23:05:48.871861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffe5d3fee03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('primary_diagnosis', sa.Text(), nullable=True),
    sa.Column('care_goals', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('last_reviewed_date', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('primary_nurse_id', sa.Integer(), nullable=True),
    sa.Column('physician_name', sa.String(length=200), nullable=True),
    sa.Column('physician_phone', sa.String(length=20), nullable=True),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('discharge_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['primary_nurse_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_plans_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_plans_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_plans_status'), ['status'], unique=False)

    op.create_table('assistance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('task_category', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('adl_type', sa.String(length=50), nullable=True),
    sa.Column('assistance_level', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('frequency_times_per_day', sa.Integer(), nullable=True),
    sa.Column('scheduled_times', sa.Text(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('assigned_role', sa.String(length=20), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('requires_two_person_assist', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('equipment_needed', sa.Text(), nullable=True),
    sa.Column('safety_precautions', sa.Text(), nullable=True),
    sa.Column('fall_risk_precautions', sa.Boolean(), nullable=True),
    sa.Column('patient_preferences', sa.Text(), nullable=True),
    sa.Column('cultural_considerations', sa.Text(), nullable=True),
    sa.Column('requires_documentation', sa.Boolean(), nullable=True),
    sa.Column('documentation_notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('discontinued_at', sa.DateTime(), nullable=True),
    sa.Column('discontinued_by_user_id', sa.Integer(), nullable=True),
    sa.Column('discontinued_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discontinued_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistance_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistance_tasks_care_plan_id'), ['care_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistance_tasks_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistance_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistance_tasks_task_category'), ['task_category'], unique=False)

    op.create_table('nursing_interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('intervention_type', sa.String(length=50), nullable=False),
    sa.Column('intervention_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('frequency_times_per_day', sa.Integer(), nullable=True),
    sa.Column('scheduled_times', sa.Text(), nullable=True),
    sa.Column('prn_indication', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('assigned_role', sa.String(length=20), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('requires_rn', sa.Boolean(), nullable=True),
    sa.Column('can_delegate', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('requires_documentation', sa.Boolean(), nullable=True),
    sa.Column('documentation_template', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('outcome_measures', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('discontinued_at', sa.DateTime(), nullable=True),
    sa.Column('discontinued_by_user_id', sa.Integer(), nullable=True),
    sa.Column('discontinued_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discontinued_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nursing_interventions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nursing_interventions_care_plan_id'), ['care_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nursing_interventions_intervention_type'), ['intervention_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_nursing_interventions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nursing_interventions_status'), ['status'], unique=False)

    op.create_table('physician_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('order_category', sa.String(length=50), nullable=True),
    sa.Column('order_text', sa.Text(), nullable=False),
    sa.Column('ordering_physician', sa.String(length=200), nullable=False),
    sa.Column('physician_npi', sa.String(length=20), nullable=True),
    sa.Column('physician_phone', sa.String(length=20), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('prn_indication', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('implementation_notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('precautions', sa.Text(), nullable=True),
    sa.Column('discontinued_at', sa.DateTime(), nullable=True),
    sa.Column('discontinued_by_user_id', sa.Integer(), nullable=True),
    sa.Column('discontinued_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discontinued_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('physician_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physician_orders_care_plan_id'), ['care_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_physician_orders_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_physician_orders_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_physician_orders_status'), ['status'], unique=False)

    op.create_table('intervention_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_notes', sa.Text(), nullable=False),
    sa.Column('patient_response', sa.Text(), nullable=True),
    sa.Column('outcome_achieved', sa.Boolean(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('reason_not_done', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_follow_up', sa.Boolean(), nullable=True),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['nursing_interventions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intervention_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intervention_completions_intervention_id'), ['intervention_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intervention_completions_patient_id'), ['patient_id'], unique=False)

    op.create_table('order_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_notes', sa.Text(), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('reason_not_done', sa.Text(), nullable=True),
    sa.Column('requires_follow_up', sa.Boolean(), nullable=True),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('physician_notified', sa.Boolean(), nullable=True),
    sa.Column('notification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['physician_orders.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_completions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_completions_patient_id'), ['patient_id'], unique=False)

    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('assisted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('patient_tolerance', sa.String(length=50), nullable=True),
    sa.Column('patient_participation', sa.String(length=50), nullable=True),
    sa.Column('safety_incidents', sa.Boolean(), nullable=True),
    sa.Column('incident_notes', sa.Text(), nullable=True),
    sa.Column('reason_not_done', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assisted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['assistance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_completions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_completions_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_completions_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_completions_patient_id'))

    op.drop_table('task_completions')
    with op.batch_alter_table('order_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_completions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_order_completions_order_id'))

    op.drop_table('order_completions')
    with op.batch_alter_table('intervention_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intervention_completions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_intervention_completions_intervention_id'))

    op.drop_table('intervention_completions')
    with op.batch_alter_table('physician_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physician_orders_status'))
        batch_op.drop_index(batch_op.f('ix_physician_orders_patient_id'))
        batch_op.drop_index(batch_op.f('ix_physician_orders_order_type'))
        batch_op.drop_index(batch_op.f('ix_physician_orders_care_plan_id'))

    op.drop_table('physician_orders')
    with op.batch_alter_table('nursing_interventions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nursing_interventions_status'))
        batch_op.drop_index(batch_op.f('ix_nursing_interventions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_nursing_interventions_intervention_type'))
        batch_op.drop_index(batch_op.f('ix_nursing_interventions_care_plan_id'))

    op.drop_table('nursing_interventions')
    with op.batch_alter_table('assistance_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistance_tasks_task_category'))
        batch_op.drop_index(batch_op.f('ix_assistance_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_assistance_tasks_patient_id'))
        batch_op.drop_index(batch_op.f('ix_assistance_tasks_care_plan_id'))

    op.drop_table('assistance_tasks')
    with op.batch_alter_table('care_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_plans_status'))
        batch_op.drop_index(batch_op.f('ix_care_plans_patient_id'))
        batch_op.drop_index(batch_op.f('ix_care_plans_facility_id'))

    op.drop_table('care_plans')
    # ### end Alembic commands ###
